### ISSUE TITLE
copy build status URL from Jenkins branch/job page

### ISSUE THREAD

**Issue by jkatnik** [jenkinsci/embeddable-build-status-plugin#177]
### What feature do you want to see added?

Hi,

I love this plugin however I find building the URL quite cumbersome.

A build status icon could be included on the Jenkins branch page and on the job page. It should copy the build status URL to the clipboard on the user's click.

**Comment by MarkEWaite** [comment]
Thanks for the suggestion @jkatnik .  I need some further clarification on what you'd like to see improved.

Are you suggesting that we should replace the current input field that shows the sample embedded status URL with a text string that has a "copy button" near it?  That would be something like the copy button that is included in the Jenkins design library plugin as shown on [the tooltips example page](https://weekly.ci.jenkins.io/design-library/Tooltips/).  That's something that has annoyed me recently, since the input field that is being used today is really not an input field at all.

## Today's page

![screencapture-mark-pc2-markwaite-net-8080-job-Tools-job-get-tools-badge-2023-03-06-06_18_38-edit](https://user-images.githubusercontent.com/156685/223121446-9d21dde7-ba4e-4546-b778-4d8db34e8a25.png)

## Future page

With apologies that I did this with a few seconds of image copy and paste

![screencapture-mark-pc2-markwaite-net-8080-job-Tools-job-get-tools-badge-2023-03-06-06_18_38-edit](https://user-images.githubusercontent.com/156685/223122246-53d06cf9-9833-4861-8e40-a260075b4bc2.png)



## Further clarification needed

When you say that a build status icon could be included on the Jenkins branch page and on the job page, I'm not sure how you envision that would work.  How would the user know that content they were copying was the embeddable build status URL?  How would the user decide which form of the embeddable build status URL should be copied?

I'm a frequent user of the markdown format version of the build status URL.  However, I don't know which type of URL is preferred by most users, so would not know which type of URL to be copied with that copy button.

**Comment by jkatnik** [comment]
Hi @MarkEWaite 

thanks for taking an interest in my request.

To depict my idea I implemented this feature as a [tampermonkey](https://www.tampermonkey.net/) [script](https://gist.github.com/jkatnik/267b617fecca55f4360cfb99053632a4).

The downside of it is that everyone needs to have the Tampermonkey addon and the script installed. I'm not sure if your plugin can modify the Jenkins Job history page, but if does then it wouldn't have had that flaw.

![image](https://user-images.githubusercontent.com/7869474/223524358-17690201-bddf-4e31-adb5-21c159f77a60.png)

**Comment by MarkEWaite** [comment]
I think you can already do that with the Markdown Formatter plugin and adding a snippet to your job description.  I'm a little surprised that they want it on that page, rather than looking at the results that are already visible on the page, but here's how I place a summary of key jobs (specific branches of specific multi-branch Pipelines) on a top level folder.  I see very quickly when one of the key jobs is not stable with this:

![screencapture-mark-pc2-markwaite-net-8080-job-Jenkins-Plugins-Folder-2023-03-07-12_26_51-edit](https://user-images.githubusercontent.com/156685/223531059-1537922a-4664-46c2-baef-fa7c6de06fbc.png)

**Comment by jkatnik** [comment]
The Markdown Formatter plugin looks promising however, Admins in my organization hesitate to install new Jenkins plugins because they are worried about Jenkins stability.

If you find this feature obsolete, then there is no problem - for my needs the script workaround is enough.

Have a nice evening :)

**Comment by MarkEWaite** [comment]
If the admins allow you to embed safe HTML in the description, you don't need the markdown formatter plugin.  The HTML from the embeddable build status plugin can be placed inside the job description as well.  I find it easier to read markdown than HTML, but understand that there are plenty of organizations that prefer HTML over markdown.

**Comment by MarkEWaite** [comment]
I'm going to close this one as "Won't do" because it would be too wide an impact on too many users.
