### ISSUE TITLE
Rename runningTime to lastRunTime

### ISSUE THREAD

**Issue by prolificcoder** [jenkinsci/embeddable-build-status-plugin#37]
I think there is  mistaking in the variable naming because when I write 
`${runningTime}` I am getting last runtime 
eg:
![image](https://user-images.githubusercontent.com/149176/51716066-17000480-1ff0-11e9-897c-21bfd1c8c576.png)

![image](https://user-images.githubusercontent.com/149176/51716063-136c7d80-1ff0-11e9-84b3-3be36135b58b.png)

**Comment by thomas-dee** [comment]
Thank you for the suggestion. I also thought about renaming that variable.

However, since we select one specific build _**last**RunTime_ would make no sense since there is only one run and **last** implies a build selection.

What do you think about `startTime`? Since the value represents the time when the build was started it is quite logical to name it what it is :-)

**Comment by prolificcoder** [comment]
may be `lastStartTime` or `previousBuildFinishtTime`

**Comment by thomas-dee** [comment]
Well, concerning the selected build, there is no `last` or `first`. It is just this one build. So I would stick with `startTime`.
